CREATE DATABASE PROJECTMANAGER;

CREATE TABLE TASK
(TASK_ID INT NOT NULL AUTO_INCREMENT,
PARENT_ID INT NULL,
PROJECT_ID INT NOT NULL,
TASK VARCHAR(100) NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
PRIORITY INT NOT NULL,
STATUS CHAR(15) NOT NULL,
PRIMARY KEY (TASK_ID),
FOREIGN KEY (PARENT_ID) REFERENCES PARENT_TASK(PARENT_ID),
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID));

CREATE TABLE PARENT_TASK
(PARENT_ID INT NOT NULL AUTO_INCREMENT,
PARENT_TASK VARCHAR(100) NOT NULL,
PROJECT_ID INT NOT NULL,
PRIMARY KEY (PARENT_ID),
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID));

CREATE TABLE PROJECT
(PROJECT_ID INT NOT NULL AUTO_INCREMENT,
PROJECT VARCHAR(100) NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
PRIORITY INT NOT NULL,
USER_ID INT NOT NULL,
STATUS CHAR(15) NOT NULL,
PRIMARY KEY (PROJECT_ID),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID));

CREATE TABLE USERS
(USER_ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
EMPLOYEE_ID INT NOT NULL,
STATUS CHAR(15) NOT NULL,
PRIMARY KEY (USER_ID));